apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: enterprise-devops-platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/kumarjadhav7010-ops/enterprise-devops-cloud-architecture'
    targetRevision: HEAD
    path: k8s/
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: production-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
