replicaCount: 3

image:
  repository: ghcr.io/kumarjadhav7010-ops/enterprise-app
  pullPolicy: IfNotPresent
  tag: "v1.2.0"

nameOverride: ""
fullnameOverride: "enterprise-devops-app"

serviceAccount:
  create: true
  name: "enterprise-sa"
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::123456789012:role/enterprise-k8s-s3-role"

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8000"

securityContext:
  runAsNonRoot: true
  runAsUser: 10001
  readOnlyRootFilesystem: true

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: devops.enterprise.io
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 15
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 80
